# Generated by Django 2.2.7 on 2019-11-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='favourite_drink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='attending',
            field=models.CharField(max_length=19),
        ),
    ]
