# Generated by Django 3.0.7 on 2020-06-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_auto_20191110_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='RSVP',
        ),
    ]
